### PR TITLE
add cambridge uni crest without text

### PR DESCRIPTION
**Pull request by RyanGibb**

### CODE REVIEW

**Comment by urbas** [comment]
This is a bit of a nitpick, but could you rename the files from `CUni_crest` to `CUni_no_text` (or `CUni_crest_only`)?

Also, could you add some instructions into `README.md` on how to replace the current crest with the one you're adding? The problem is that if you naively replace the `CUni` file with `CUni_crest` you get this:
WithoutText

The crest is too big. Instructions on how to make it smaller and fix nicely would be super welcome. :pray:

**Comment by RyanGibb** [comment]
Done:) I've added instructions on how to replace the college crest with the uni crest (also referred to crests as 'shields').

**Comment by urbas** [comment]
Fantastic! Thank you very much for this!

**Comment by RyanGibb** [comment]
No problem!

**Comment by RyanGibb** [comment]
Some relevant news: the University of Cambridge has banned their arms/shield/logo appearing on PhD dissertations.

> Please note that the University logo should not be used as your thesis is your work and not the work of the University. If you wish to use a logo on your title page, you are advised to ask your College about the use of their logo.

[0] https://www.cambridgestudents.cam.ac.uk/your-course/examinations/graduate-exam-information/submitting-and-examination/phd-msc-mlitt/submit

**Comment by urbas** [comment]
Oh my, nicely spotted. I'll open an issue for this.

**Comment by RyanGibb** [comment]
Yeah, it's a recent and rather unfortunate decision: https://www.varsity.co.uk/news/23128

**Pull request merged**
